### ISSUE TITLE
Project status out-of-date

### ISSUE THREAD

**Issue by atrophiedbrain** [mtl-brainhack-school-2019/AtrophiedBrain-machine-learning-parameter-estimation#1]
The project details need to be updated now that it has been forked.

**Comment by atrophiedbrain** [comment]
A new branch should be created for this year's work that can later be merged back.

**Comment by atrophiedbrain** [comment]
@pbellec Is this the appropriate way of continuing a project from last year's BrainHack school.
Also, is this how I'm supposed to tag you?

**Comment by lunebellec** [comment]
Forking is enough, you can definitely work from the master branch from now on.
