### ISSUE TITLE
Add noise to training data

### ISSUE THREAD

**Issue by atrophiedbrain** [mtl-brainhack-school-2019/AtrophiedBrain-machine-learning-parameter-estimation#2]
I am currently adding random noise with a mean of 0 and a standard deviation of each training variable divided by 5. 

This was my first attempt, perhaps some investigation of a better noise term should be researched.

**Comment by atrophiedbrain** [comment]
@illdopejake What would you recommend as a noise term for each simulated variable?

**Comment by illdopejake** [comment]
I haven't done this too often, but as far as I understand it's standard to add gaussian noise. You can do this pretty easily with numpy: np.random.normal. Here's a clean example of this: https://stackoverflow.com/questions/46093073/adding-gaussian-noise-to-a-dataset-of-floating-points-and-save-it-python/46093600#46093600

It seems like you're more or less doing this already though. I've never really done anything beyond that but we could look into it together if you'd like.
