### ISSUE TITLE
add deliverables

### ISSUE THREAD

**Issue by lunebellec** [mtl-brainhack-school-2019/AtrophiedBrain-machine-learning-parameter-estimation#8]
You are currently quite vague about the deliverables. Are you going to make a notebook, a script? will you have a description of your dependencies? will you deploy those resources somewhere (zenodo, binder etc). Same for data btiw

**Comment by atrophiedbrain** [comment]
Thank you for the suggestion, Pierre. I have added a deliverable section to the project description.
